### ISSUE TITLE
[Fix] 엑셀 상품 업로드 Lambda 함수 수정

### ISSUE THREAD

**Issue by chanhyeokseo** [Repick-official/repick-server-v2#106]
# [Fix] 엑셀 상품 업로드 Lambda 함수 수정

### 📝 Description

---

#105 #103 에서 이어집니다.

변경된 기능에 따라 엑셀에서 자동 상품 등록 로직을 변경합니다.

- 엑셀로 상품 업로드 시 해당 옷장 정리에 대한 clothingSalesState을 PRODUCT_REGISTERED로 업데이트
- isBoxCollect, clothingSalesId 삭제 및 clothingSalesCount(회차) 추가

### ✅ To Do List 

---

- [x] 엑셀로 상품 업로드 시 해당 옷장 정리에 대한 clothingSalesState을 PRODUCT_REGISTERED로 업데이트
- [x]  isBoxCollect, clothingSalesId 삭제 및 clothingSalesCount(회차) 추가
- [x] 리젝 여부 추가
- [x] #116
- [x] 리젝 상품 조회 API

**Comment by mushroom1324** [comment]
구현 완료로 이슈를 닫습니다.

**Comment by chanhyeokseo** [comment]
구현 완료로 이슈를 닫습니다.
