### ISSUE TITLE
Readme.md 작성

### ISSUE THREAD

**Issue by chanhyeokseo** [Repick-official/repick-server-v2#134]
# Readme.md 작성

### 📝 Description

---
여러분 저희도 레포지토리 readme 작성합시다 :)

어떤식으로 작성할지 의견 주세요!!

### ✅ Things to add

---
- [ ] 인프라 아키텍처 
- [ ] 기술 스택
- [ ] 컨택 정보

**Comment by sky980221** [comment]
Git Convention 같은거 적어놓아도 좋을 것 같아용 ㅎㅎ

**Comment by sky980221** [comment]
다른 레포지토리 보면 

|
|
|---------Domain 
|---------Global 
이런식으로 프로젝트 구성도 Readme에 적는 경우가 있던데 그건 어떠하신지요 ?

**Comment by chanhyeokseo** [comment]
수상내역?ㅎㅎ
